# Generated by Django 4.0.5 on 2022-07-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_author_post_id_for_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type_title',
            field=models.CharField(choices=[('Фильм', 'Фильм'), ('Аниме', 'Аниме'), ('Мульт', 'Мульт')], default='Не выбрано', max_length=11),
        ),
    ]
