# Generated by Django 4.0.5 on 2022-07-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_type_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type_title',
            field=models.CharField(choices=[('Книга', 'Книга'), ('Фильм', 'Фильм'), ('Сериал', 'Сериал'), ('Аниме', 'Аниме'), ('Мульт', 'Мульт'), ('Игра', 'Игра')], default='Не выбрано', max_length=11),
        ),
    ]
