# Generated by Django 4.0.5 on 2022-07-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('link', models.TextField(verbose_name='Ссылка')),
                ('lastpage', models.IntegerField(verbose_name='Последняя страница')),
                ('created_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Планирую', 'Планирую'), ('Читаю', 'Читаю'), ('Прочитано', 'Прочитано'), ('Заброшено', 'Заброшено')], default='Планирую', max_length=10)),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('status', models.CharField(choices=[('Планирую', 'Планирую'), ('Смотрю', 'Смотрю'), ('Просмотрено', 'Просмотрено'), ('Заброшено', 'Заброшено')], default='Планирую', max_length=11)),
                ('link', models.TextField(verbose_name='Ссылка')),
                ('last_hour', models.IntegerField(default=0, verbose_name='Час')),
                ('last_minute', models.IntegerField(default=0, verbose_name='Минута')),
                ('last_serie', models.IntegerField(default=1, verbose_name='Последняя серия')),
                ('created_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ['name'],
            },
        ),
    ]
