# Generated by Django 4.0.5 on 2022-07-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_serial_country_serial_alter_serial_type_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serial',
            name='type_serial',
            field=models.CharField(choices=[('Сериал', 'Сериал'), ('Аниме', 'Аниме'), ('Мульт', 'Мульт')], default='Не выбрано', max_length=11),
        ),
    ]
