# Generated by Django 3.2.5 on 2023-01-01 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_book_id_for_user_film_id_for_user'),
        ('main', '0007_alter_serial_type_serial'),
    ]

    operations = [
    ]
